services:
  etna_mysql_db:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'marketplace'
      MYSQL_USER: 'marketplace'
      MYSQL_PASSWORD: 'marketplace'
    volumes:
      - /marketplace/script.sql:/docker-entrypoint-initdb.d

